#!/bin/bash

set -ex

# Figure out the absolute path of the dotfiles directory
DOTFILESDIRREL="$(dirname "$0")"
cd $DOTFILESDIRREL/..
DOTFILESDIR="$(pwd -P)"

HOMEDOTFILES="$HOME/.dotfiles"
ln -sf "$DOTFILESDIR" "$HOMEDOTFILES"
cat "$DOTFILESDIR/.bashrc" >> "$HOME/.bashrc"

git config --global core.editor "vim"

if [[ -d "/workspaces/github" ]]; then
  export IS_GH_GH=true
  cd "/workspaces/github"
  # bin/setup-codespaces
fi
